# Uncomment this line to define a global platform for your project
use_frameworks!
platform :ios, '8.0'

pod 'Alamofire'
pod 'SwiftyJSON'
pod 'SVProgressHUD'
pod 'TOWebViewController'
pod 'PageMenu'
pod "HTMLReader"
pod "PullToRefreshSwift"
