# Uncomment this line to define a global platform for your project
platform :ios, '8.3'
use_frameworks!

pod 'SVProgressHUD'
pod 'RealmSwift'

target 'YShopping_Swift' do

end

target 'YShopping_SwiftTests' do

end

